spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&antuReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    hikari:
      maximum-pool-size: 200
      minimum-idle: 20

